name: devcycle_flutter_client_sdk
description: Official Flutter Client SDK for DevCycle. Supports iOS and Android.
version: "1.10.0"
homepage: https://www.devcycle.com
repository: https://github.com/DevCycleHQ/flutter-client-sdk
documentation: https://docs.devcycle.com/docs/sdk/client-side-sdks/flutter
issue_tracker: https://github.com/DevCycleHQ/flutter-client-sdk/issues

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  logger: ^2.4.0
  plugin_platform_interface: ^2.1.8
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

platforms:
  android:
  ios:

flutter:
  plugin:
    platforms:
      android:
        package: com.devcycle.devcycle_flutter_client_sdk
        pluginClass: DevCycleFlutterClientSdkPlugin
      ios:
        pluginClass: DevCycleFlutterClientSdkPlugin
